### ISSUE TITLE
Enable point extraction from area

### ISSUE THREAD

**Issue by Peter9192** [phenology/springtime#38]
This could work as a `filter`, `preprocess`, or some other name function that can be called within the load function, e.g.

```
datasets:
    modistools:
        area: ....
    preprocess:
        extract_points:
            sites: ...
```

could support methods like 'nearest', 'mean' with some 'padding_radius', or other.
